#ifndef _DIRTY_DEFINATIONS
#define _DIRTY_DEFINATIONS

#define MZ_IDC_TOOLBAR1     101

#define IDC_PPM_CAPTURE     102
#define IDC_PPM_BROWSE      103

#define IDC_MENU_EXIT       0
#define IDC_MENU_REFRESH    1
#define IDC_MENU_FULLSCREEN 2
#define IDC_MENU_OPTIMIZE     3
#define IDC_MENU_MENU       4
#define IDC_MENU_M_WALLPAPER    5
#define IDC_MENU_M_CAPTURE  6
#define IDC_MENU_M_MANGA    7
#define IDC_MENU_M_BROWSE   8
#define IDC_MENU_MANGA_SINGAL   9
#define IDC_MENU_MANGA_NATIVE   10
#define IDC_MENU_MANGA_NIPPON   11
//#define IDC_MENU_MANGA_PHOTO    12


#define IDT_SOMEMARKTIMEOUT 104
#define IDT_SOMEHINTTIMEOUT 105

#define WM_MZ_TOUCHNOTIFY   59369822

#endif
